/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.GUI;

import edu.neu.csye6200.SystemModel.AbstractCarRentalSystemAPI;
import edu.neu.csye6200.SystemModel.CarRentalSystemBase;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author varad
 */
public class CreateAccountJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountJFrame
     */
    
    private String type;
    public CreateAccountJFrame() {
        initComponents();
    }
    
    public CreateAccountJFrame(String type) {
        this.type = type;
        initComponents();
    }
    
    final static String DATE_FORMAT = "MM/dd/yyyy";

    /**
     * Date format: "MM/dd/yyyy"
     * @param date
     * @return 
     */
    public boolean isDateNotValid(String date) 
    {
            try {
                DateFormat df = new SimpleDateFormat(DATE_FORMAT);
                df.setLenient(false);
                df.parse(date);
                return false;
            } catch (ParseException e) {
                return true;
            }
    }
    
    /**
     * Email format: something@something.com
     * @param email
     * @return 
     */
    public boolean isEmailNotValid(String email){
        String regex = "^(.+)@(.+)$";//"^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        boolean result;
        if(email.matches(regex)){
            result = false;
        }
        else {
            result = true;
        }
        return result;
    }
    
    /**
     * Password constraints:
     * 1. It contains at least 8 characters and at most 20 characters.
     * 2. It contains at least one digit.
     * 3. It contains at least one upper case alphabet.
     * 4. It contains at least one lower case alphabet.
     * 5. It contains at least one special character which includes !@#$%&*()-+=^.
     * 6. It doesn’t contain any white space.
     * @param password
     * @return 
     */
    public boolean isPasswordNotValid(String password){
        String regex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&-+=()])(?=\\S+$).{8,20}$";

        boolean result;
        if(password.matches(regex)){
            result = false;
        }
        else{
            result = true;
        }
        return result;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccountJLabel = new javax.swing.JLabel();
        homeJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        lesseePhoneNoJTextField = new javax.swing.JTextField();
        DateOfBirthDriverJLabel = new javax.swing.JLabel();
        phoneNoDriverJLabel = new javax.swing.JLabel();
        systemPasswordLoginJLabel3 = new javax.swing.JLabel();
        lesseePasswordJTextField = new javax.swing.JTextField();
        systemEmailidLoginJLabel3 = new javax.swing.JLabel();
        lesseeNameJLabel = new javax.swing.JLabel();
        lesseeEmailidJTextField = new javax.swing.JTextField();
        lesseeNameJTextField = new javax.swing.JTextField();
        lesseeCreateAccountJButton = new javax.swing.JButton();
        licenseNumberLesseeJLabel = new javax.swing.JLabel();
        lesseeLicenseNumberJTextField = new javax.swing.JTextField();
        lesseeDateOfBirthJTextField = new javax.swing.JTextField();
        validationJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createAccountJLabel.setFont(new java.awt.Font("Garamond", 3, 24)); // NOI18N
        createAccountJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAccountJLabel.setText("Create Account");
        createAccountJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createAccountJLabel.setName("createAccountJLabel"); // NOI18N

        homeJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        homeJButton.setText("Home");
        homeJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        homeJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        homeJButton.setName("homeJButton"); // NOI18N
        homeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        backJButton.setText("Back");
        backJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        backJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        backJButton.setName("backJButton"); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        lesseePhoneNoJTextField.setName("renterPasswordLoginJTextField"); // NOI18N

        DateOfBirthDriverJLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        DateOfBirthDriverJLabel.setText("Date Of Birth");
        DateOfBirthDriverJLabel.setName("DateOfBirthDriverJLabel"); // NOI18N

        phoneNoDriverJLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        phoneNoDriverJLabel.setText("Phone No.");
        phoneNoDriverJLabel.setName("phoneNoDriverJLabel"); // NOI18N

        systemPasswordLoginJLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        systemPasswordLoginJLabel3.setText("Password");
        systemPasswordLoginJLabel3.setName("systemPasswordLoginJLabel"); // NOI18N

        lesseePasswordJTextField.setName("lesseePasswordJTextField"); // NOI18N

        systemEmailidLoginJLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        systemEmailidLoginJLabel3.setText("Email-Id");
        systemEmailidLoginJLabel3.setName("systemEmailidLoginJLabel"); // NOI18N

        lesseeNameJLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lesseeNameJLabel.setText("Name");
        lesseeNameJLabel.setName("lesseeNameJLabel"); // NOI18N

        lesseeEmailidJTextField.setName("systemEmailidLoginJTextField"); // NOI18N

        lesseeNameJTextField.setName("lesseeNameJTextField"); // NOI18N

        lesseeCreateAccountJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lesseeCreateAccountJButton.setText("Create Account");
        lesseeCreateAccountJButton.setName("lesseeCreateAccountJButton"); // NOI18N
        lesseeCreateAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesseeCreateAccountJButtonActionPerformed(evt);
            }
        });

        licenseNumberLesseeJLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        licenseNumberLesseeJLabel.setText("License No.");
        licenseNumberLesseeJLabel.setName("licenseNumberLesseeJLabel"); // NOI18N

        lesseeLicenseNumberJTextField.setName("lesseeLicenseNumberJTextField"); // NOI18N

        lesseeDateOfBirthJTextField.setName("lesseeDateOfBirthJTextField"); // NOI18N
        lesseeDateOfBirthJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesseeDateOfBirthJTextFieldActionPerformed(evt);
            }
        });

        validationJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        validationJLabel.setForeground(new java.awt.Color(255, 0, 0));
        validationJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lesseeNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNoDriverJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(systemEmailidLoginJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(systemPasswordLoginJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licenseNumberLesseeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateOfBirthDriverJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lesseeEmailidJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lesseePhoneNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lesseeDateOfBirthJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(lesseeLicenseNumberJTextField)
                            .addComponent(lesseeNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(homeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lesseePasswordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lesseeCreateAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(validationJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createAccountJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(createAccountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validationJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lesseeNameJLabel)
                    .addComponent(lesseeNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseNumberLesseeJLabel)
                    .addComponent(lesseeLicenseNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateOfBirthDriverJLabel)
                    .addComponent(lesseeDateOfBirthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNoDriverJLabel)
                    .addComponent(lesseePhoneNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(systemEmailidLoginJLabel3)
                    .addComponent(lesseeEmailidJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(systemPasswordLoginJLabel3)
                    .addComponent(lesseePasswordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lesseeCreateAccountJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(backJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeJFrame hjf = new HomeJFrame();
        hjf.setVisible(true);
        
    }//GEN-LAST:event_homeJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CreateAccountLoginJFrame_new hjf = new CreateAccountLoginJFrame_new(this.type);
        hjf.setVisible(true);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void lesseeCreateAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesseeCreateAccountJButtonActionPerformed
        // TODO add your handling code here:
        
        DateFormat dateFormatter = new SimpleDateFormat("MM/dd/yyyy");
        
        if(lesseeNameJTextField.getText().isEmpty()){
            validationJLabel.setText("Name field cannot be Empty!");
        }
        else if(lesseeLicenseNumberJTextField.getText().isEmpty()){
            validationJLabel.setText("License number cannot be Empty!");
        }
        else if(lesseeDateOfBirthJTextField.getText().isEmpty()){
            validationJLabel.setText("Date of birth cannot be Empty!");
        }
        else if(lesseePhoneNoJTextField.getText().isEmpty()){
            validationJLabel.setText("Phone number cannot be Empty!");
        }
        else if(lesseeEmailidJTextField.getText().isEmpty()){
            validationJLabel.setText("Email Id cannot be Empty!");
        }
        else if(lesseePasswordJTextField.getText().isEmpty()){
            validationJLabel.setText("Password cannot be Empty!");
        }
        else if(isDateNotValid(lesseeDateOfBirthJTextField.getText())){
            validationJLabel.setText("Date of Birth not Valid!");
        }
        else if(isEmailNotValid(lesseeEmailidJTextField.getText())){
            validationJLabel.setText("Email is not Valid!");
        }
        else if(isPasswordNotValid(lesseePasswordJTextField.getText())){
            validationJLabel.setText("Password is not Valid!");
        }
        else{
            
            validationJLabel.setText("");
            
            StringBuilder sb = new StringBuilder();

            sb.append(lesseeNameJTextField.getText()).append(",");
            sb.append(lesseeLicenseNumberJTextField.getText()).append(",");
            sb.append(lesseeDateOfBirthJTextField.getText()).append(",");
            sb.append(lesseePhoneNoJTextField.getText()).append(",");
            sb.append(lesseeEmailidJTextField.getText()).append(",");
            sb.append(lesseePasswordJTextField.getText());

            String personData = sb.toString();

            AbstractCarRentalSystemAPI acra = AbstractCarRentalSystemAPI.getObject();

            if(type.equalsIgnoreCase("Lessee")) {
                acra.addLessee(personData);
            } else if(type.equalsIgnoreCase("Renter")) {
                acra.addRenter(personData);
            }
            
            validationJLabel.setForeground(Color.blue);
            validationJLabel.setText(type+" Account Sucessfully Created!");

            JOptionPane.showMessageDialog(null, "Account created successfully.");
            this.dispose();
            HomeJFrame hjf = new HomeJFrame();
            hjf.setVisible(true);

        }
    }//GEN-LAST:event_lesseeCreateAccountJButtonActionPerformed

    private void lesseeDateOfBirthJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesseeDateOfBirthJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lesseeDateOfBirthJTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateOfBirthDriverJLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel createAccountJLabel;
    private javax.swing.JButton homeJButton;
    private javax.swing.JButton lesseeCreateAccountJButton;
    private javax.swing.JTextField lesseeDateOfBirthJTextField;
    private javax.swing.JTextField lesseeEmailidJTextField;
    private javax.swing.JTextField lesseeLicenseNumberJTextField;
    private javax.swing.JLabel lesseeNameJLabel;
    private javax.swing.JTextField lesseeNameJTextField;
    private javax.swing.JTextField lesseePasswordJTextField;
    private javax.swing.JTextField lesseePhoneNoJTextField;
    private javax.swing.JLabel licenseNumberLesseeJLabel;
    private javax.swing.JLabel phoneNoDriverJLabel;
    private javax.swing.JLabel systemEmailidLoginJLabel3;
    private javax.swing.JLabel systemPasswordLoginJLabel3;
    private javax.swing.JLabel validationJLabel;
    // End of variables declaration//GEN-END:variables
}
