///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package edu.neu.csye6200.GUI;
//
///**
// *
// * @author manish
// */
//public class CreateAccountLoginJFrame extends javax.swing.JFrame {
//
//    private String type;
//    /**
//     * Creates new form LoginSignUpJFrame
//     */
//    
//    public CreateAccountLoginJFrame() {
//        initComponents();
//    }
//
//    public CreateAccountLoginJFrame(String type) {
//        this.type = type; 
//        initComponents();
//    }
//        
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        loginJButton = new javax.swing.JButton();
//        createAccountJButton = new javax.swing.JButton();
//        backLoginJButton1 = new javax.swing.JButton();
//        homeLoginJButton1 = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        loginJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
//        loginJButton.setText("Login");
//        loginJButton.setActionCommand("loginJButton");
//        loginJButton.setMaximumSize(new java.awt.Dimension(150, 50));
//        loginJButton.setMinimumSize(new java.awt.Dimension(150, 50));
//        loginJButton.setName("loginJButton"); // NOI18N
//        loginJButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                loginJButtonActionPerformed(evt);
//            }
//        });
//
//        createAccountJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
//        createAccountJButton.setText("Create Account");
//        createAccountJButton.setActionCommand("createAccountJButton");
//        createAccountJButton.setMaximumSize(new java.awt.Dimension(100, 50));
//        createAccountJButton.setMinimumSize(new java.awt.Dimension(100, 50));
//        createAccountJButton.setName("createAccountJButton"); // NOI18N
//        createAccountJButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                createAccountJButtonActionPerformed(evt);
//            }
//        });
//
//        backLoginJButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
//        backLoginJButton1.setText("Back");
//        backLoginJButton1.setMaximumSize(new java.awt.Dimension(150, 50));
//        backLoginJButton1.setMinimumSize(new java.awt.Dimension(150, 50));
//        backLoginJButton1.setName("backLoginJButton"); // NOI18N
//        backLoginJButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                backLoginJButton1ActionPerformed(evt);
//            }
//        });
//
//        homeLoginJButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
//        homeLoginJButton1.setText("Home");
//        homeLoginJButton1.setMaximumSize(new java.awt.Dimension(150, 50));
//        homeLoginJButton1.setMinimumSize(new java.awt.Dimension(150, 50));
//        homeLoginJButton1.setName("homeLoginJButton"); // NOI18N
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addContainerGap(190, Short.MAX_VALUE)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(backLoginJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(18, 18, 18)
//                        .addComponent(homeLoginJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                        .addComponent(createAccountJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
//                        .addComponent(loginJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                .addGap(114, 114, 114))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(59, 59, 59)
//                .addComponent(createAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(29, 29, 29)
//                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                    .addComponent(backLoginJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(homeLoginJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addGap(11, 11, 11)))
//                .addContainerGap(36, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void createAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountJButtonActionPerformed
//        // TODO add your handling code here:
//        this.dispose();
//        if(type.equalsIgnoreCase("System")) {
//            SystemCreateAccountJFrame scajf = new SystemCreateAccountJFrame();
//            scajf.setVisible(true);
//            return;
//        }
//        CreateAccountJFrame createAccountJFrame = new CreateAccountJFrame(this.type);
//        createAccountJFrame.setVisible(true);
//    }//GEN-LAST:event_createAccountJButtonActionPerformed
//
//    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
//        // TODO add your handling code here:
//        this.dispose();
//        LoginJFrame loginJFrame = new LoginJFrame(this.type);
//        loginJFrame.setVisible(true);
//    }//GEN-LAST:event_loginJButtonActionPerformed
//
//    private void backLoginJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginJButton1ActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_backLoginJButton1ActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreateAccountLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreateAccountLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreateAccountLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreateAccountLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CreateAccountLoginJFrame().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton backLoginJButton1;
//    private javax.swing.JButton createAccountJButton;
//    private javax.swing.JButton homeLoginJButton1;
//    private javax.swing.JButton loginJButton;
//    // End of variables declaration//GEN-END:variables
//}
