/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.GUI;

/**
 *
 * @author varad
 */
public class CreateAccountLoginJFrame_new extends javax.swing.JFrame {

    
    private String type;
    /**
     * Creates new form CreateAccountLoginJFrame_new
     */
    public CreateAccountLoginJFrame_new() {
        initComponents();
    }
    
    public CreateAccountLoginJFrame_new(String type) {
        this.type = type;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        loginJButton = new javax.swing.JButton();
        homeJButton = new javax.swing.JButton();
        createAccountJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        backJButton.setText("Back");
        backJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        backJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        backJButton.setName("backJButton"); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        loginJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        loginJButton.setText("Login");
        loginJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        loginJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        loginJButton.setName("loginJButton"); // NOI18N
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        homeJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        homeJButton.setText("Home");
        homeJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        homeJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        homeJButton.setName("homeSystemLoginJButton"); // NOI18N
        homeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJButtonActionPerformed(evt);
            }
        });

        createAccountJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        createAccountJButton.setText("Create Account");
        createAccountJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        createAccountJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        createAccountJButton.setName("homeSystemLoginJButton"); // NOI18N
        createAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(homeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(createAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeJFrame hjf = new HomeJFrame();
        hjf.setVisible(true);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginJFrame loginJFrame = new LoginJFrame(this.type);
        loginJFrame.setVisible(true);
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void homeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeJFrame hjf = new HomeJFrame();
        hjf.setVisible(true);
    }//GEN-LAST:event_homeJButtonActionPerformed

    private void createAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if(this.type.equalsIgnoreCase("System")) {
            SystemCreateAccountJFrame scajf = new SystemCreateAccountJFrame();
            scajf.setVisible(true);
            return;
        }
        CreateAccountJFrame createAccountJFrame = new CreateAccountJFrame(this.type);
        createAccountJFrame.setVisible(true);
    }//GEN-LAST:event_createAccountJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountLoginJFrame_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountLoginJFrame_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountLoginJFrame_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountLoginJFrame_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountLoginJFrame_new().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createAccountJButton;
    private javax.swing.JButton homeJButton;
    private javax.swing.JButton loginJButton;
    // End of variables declaration//GEN-END:variables
}
