/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.GUI;

/**
 *
 * @author varad
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    public HomeJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carRentalJLabel = new javax.swing.JLabel();
        systemCreateAccountJButton = new javax.swing.JButton();
        renterCreateAccountJButton = new javax.swing.JButton();
        driverCreateAccountJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        carRentalJLabel.setFont(new java.awt.Font("Garamond", 3, 24)); // NOI18N
        carRentalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carRentalJLabel.setText("Car Rental System");
        carRentalJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        carRentalJLabel.setName("carRentalJLabel"); // NOI18N

        systemCreateAccountJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        systemCreateAccountJButton.setText("System");
        systemCreateAccountJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        systemCreateAccountJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        systemCreateAccountJButton.setName("systemCreateAccountJButton"); // NOI18N
        systemCreateAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemCreateAccountJButtonActionPerformed(evt);
            }
        });

        renterCreateAccountJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        renterCreateAccountJButton.setText("Renter");
        renterCreateAccountJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        renterCreateAccountJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        renterCreateAccountJButton.setName("renterCreateAccountJButton"); // NOI18N
        renterCreateAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renterCreateAccountJButtonActionPerformed(evt);
            }
        });

        driverCreateAccountJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        driverCreateAccountJButton.setText("Lessee");
        driverCreateAccountJButton.setActionCommand("driverCreateAccountJButton");
        driverCreateAccountJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        driverCreateAccountJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        driverCreateAccountJButton.setName("driverCreateAccountJButton"); // NOI18N
        driverCreateAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverCreateAccountJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(carRentalJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(systemCreateAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renterCreateAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverCreateAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carRentalJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(driverCreateAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(renterCreateAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(systemCreateAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void systemCreateAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemCreateAccountJButtonActionPerformed
        // TODO add your handling code here:
        openLoginSignUpPage("System");
    }//GEN-LAST:event_systemCreateAccountJButtonActionPerformed

    private void renterCreateAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renterCreateAccountJButtonActionPerformed
        // TODO add your handling code here:
        openLoginSignUpPage("Renter");
    }//GEN-LAST:event_renterCreateAccountJButtonActionPerformed

    private void driverCreateAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverCreateAccountJButtonActionPerformed
        // TODO add your handling code here:
        openLoginSignUpPage("Lessee");
    }//GEN-LAST:event_driverCreateAccountJButtonActionPerformed

    /**
     * MAIN for Application
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    public void openLoginSignUpPage(String type) {
        this.dispose();
        CreateAccountLoginJFrame_new loginSignUpJFrame = new CreateAccountLoginJFrame_new(type);
        loginSignUpJFrame.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carRentalJLabel;
    private javax.swing.JButton driverCreateAccountJButton;
    private javax.swing.JButton renterCreateAccountJButton;
    private javax.swing.JButton systemCreateAccountJButton;
    // End of variables declaration//GEN-END:variables
}
