/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.GUI;

import edu.neu.csye6200.SystemModel.AbstractBookingAPI;
import edu.neu.csye6200.SystemModel.AbstractCarAPI;
import edu.neu.csye6200.SystemModel.AbstractCarRentalSystemAPI;
import edu.neu.csye6200.SystemModel.AbstractPersonAPI;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manish
 */
public class LesseeBookingJFrame extends javax.swing.JFrame {

    AbstractPersonAPI person;
    /**
     * Creates new form LesseeBookingJFrame
     */
    public LesseeBookingJFrame() {
        initComponents();
    }

    public LesseeBookingJFrame(AbstractPersonAPI person) {
        this.person = person;
        initComponents();
        lesseeBookingLabel.setText("Hello " + this.person.getName());
        loadCarTable();
        loadBookingTable();
        bookingDate.setToolTipText("Format: MM/DD/YYYY");
        startBookingTime.setToolTipText("Format: HH:MM:SS");
    }
    
    public void loadCarTable() {
        DefaultTableModel model = (DefaultTableModel) carListAll.getModel();
        model.setRowCount(0);
        AbstractCarRentalSystemAPI
                .getObject()
                .getAllCars().stream()
                    .forEach(car -> {
                        Object[] row = new Object[3];
                        row[0] = car;
                        row[1] = car.getName();
                        row[2] = car.getRentPerHour();
                        model.addRow(row);
                    });
        carListAll.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void loadBookingTable() {
        DefaultTableModel model = (DefaultTableModel) bookingList.getModel();
        model.setRowCount(0);
        AbstractCarRentalSystemAPI
                .getObject()
                .getAllBookings().stream()
                    .filter(booking -> booking.getLesseeId().equals(this.person.getPersonId()))
                    .forEach(booking -> {
                        AbstractCarAPI bookedCar = AbstractCarRentalSystemAPI.getObject()
                                .getCar(booking.getCarId()); 
                        Object[] row = new Object[6];
                        row[0] = bookedCar;
                        row[1] = bookedCar.getName();
                        row[2] = booking;
                        row[3] = booking.getDate();
                        row[4] = booking.getStartTime();
                        row[5] = booking.getEndTime();
                        model.addRow(row);
                    });
        bookingList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backSystemLoginJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        carListAll = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lesseeBookingLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bookingDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        startBookingTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        endBookingTime = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingList = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backSystemLoginJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        backSystemLoginJButton.setText("Logout");
        backSystemLoginJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        backSystemLoginJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        backSystemLoginJButton.setName("backSystemLoginJButton"); // NOI18N
        backSystemLoginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSystemLoginJButtonActionPerformed(evt);
            }
        });

        carListAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Car Company ", "Car Name", "Rent per hour"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(carListAll);
        if (carListAll.getColumnModel().getColumnCount() > 0) {
            carListAll.getColumnModel().getColumn(0).setResizable(false);
            carListAll.getColumnModel().getColumn(1).setResizable(false);
            carListAll.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setText("Cars");

        lesseeBookingLabel.setText("LesseeBookingLabel");

        jButton1.setText("Book ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Manage Your Bookings");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Date");

        bookingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingDateActionPerformed(evt);
            }
        });

        jLabel3.setText("Start Time");

        jLabel4.setText("End Time");

        bookingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Car Company ", "Car Name", "Fee", "Date", "Start Time", "End Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bookingList);
        if (bookingList.getColumnModel().getColumnCount() > 0) {
            bookingList.getColumnModel().getColumn(0).setResizable(false);
            bookingList.getColumnModel().getColumn(1).setResizable(false);
            bookingList.getColumnModel().getColumn(2).setResizable(false);
            bookingList.getColumnModel().getColumn(3).setResizable(false);
            bookingList.getColumnModel().getColumn(4).setResizable(false);
            bookingList.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel5.setText("Your Bookings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lesseeBookingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(endBookingTime, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(startBookingTime)
                                    .addComponent(bookingDate)))
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(backSystemLoginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(536, 536, 536)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lesseeBookingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(bookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(startBookingTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(endBookingTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(319, 319, 319)
                    .addComponent(backSystemLoginJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backSystemLoginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSystemLoginJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeJFrame hjf = new HomeJFrame();
        hjf.setVisible(true);
    }//GEN-LAST:event_backSystemLoginJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(carListAll.getModel().getRowCount() == 0 || carListAll.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a car to book.");
            return;
        }
        else if(bookingDate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a date to book.");
            return;
        }
        else if(startBookingTime.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter start time to book.");
            return;
        }
        else if(endBookingTime.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter end time to book.");
            return;
        }
        else if(isDateNotValid(bookingDate.getText())) {
            JOptionPane.showMessageDialog(null, "Date is not valid.");
            return;            
        } // add for isTimeNotValid - startTime and endTime as well
        
        AbstractCarAPI selectedCar = (AbstractCarAPI) carListAll.getValueAt(carListAll.getSelectedRow(), 0);
        
        StringBuilder sb = new StringBuilder();
        sb.append(this.person.getPersonId()).append(",");
        sb.append(selectedCar.getCarId()).append(",");
        sb.append(bookingDate.getText()).append(",");
        sb.append(startBookingTime.getText()).append(",");
        sb.append(endBookingTime.getText());
        
        try {
            AbstractCarRentalSystemAPI.getObject().addBooking(sb.toString());
            JOptionPane.showMessageDialog(null, "Booking added successfully!"); 
            this.dispose();
            LesseeBookingJFrame lbjf = new LesseeBookingJFrame(person);
            lbjf.setVisible(true);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Some error occurred!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingDateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(bookingList.getModel().getRowCount() == 0 || bookingList.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a booking.");
            return;
        }
        AbstractBookingAPI selectedBooking = (AbstractBookingAPI) bookingList.getValueAt(bookingList.getSelectedRow(), 2);
        
        this.dispose();
        ManageBookingJFrame mbjf = new ManageBookingJFrame(this.person, selectedBooking);
        mbjf.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    final static String DATE_FORMAT = "MM/dd/yyyy";
    final static String TIME_FORMAT = "HH:MM:SS";

//                date_ = LocalDate.parse(scLine.next(), DateTimeFormatter.ofPattern(DATE_FORMAT));
//            start_time = LocalTime.parse(scLine.next(), DateTimeFormatter.ofPattern("H:mm:ss"));
//            end_time = LocalTime.parse(scLine.next(), DateTimeFormatter.ofPattern(TIME_FORMAT);
    /**
     * Date format: "MM/dd/yyyy"
     * @param date
     * @return 
     */
    public boolean isDateNotValid(String date) 
    {
            try {
                DateFormat df = new SimpleDateFormat(DATE_FORMAT);
                df.setLenient(false);
                df.parse(date);
                return false;
            } catch (ParseException e) {
                return true;
            }
    }
        
//    public boolean isTimeNotValid(String date) 
//    {
//
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LesseeBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LesseeBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LesseeBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LesseeBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LesseeBookingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backSystemLoginJButton;
    private javax.swing.JTextField bookingDate;
    private javax.swing.JTable bookingList;
    private javax.swing.JTable carListAll;
    private javax.swing.JTextField endBookingTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lesseeBookingLabel;
    private javax.swing.JTextField startBookingTime;
    // End of variables declaration//GEN-END:variables
}
