/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.GUI;

import edu.neu.csye6200.SystemModel.AbstractCarRentalSystemAPI;
import edu.neu.csye6200.SystemModel.AbstractPersonAPI;
import edu.neu.csye6200.SystemModel.CarRentalSystemBase;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author varad
 */
public class LoginJFrame extends javax.swing.JFrame {

    private String type;
    /**
     * Creates new form LoginView
     */
    public LoginJFrame() {
        initComponents();
    }

    public LoginJFrame(String type) {
        initComponents();
        this.type = type;
    }
    
    /**
     * Email format: something@something.com
     * @param email
     * @return 
     */
    public boolean isEmailNotValid(String email){
        String regex = "^(.+)@(.+)$"; //"^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        boolean result;
        if(email.matches(regex)){
            result = false;
        }
        else {
            result = true;
        }
        return result;
    }
    
    /**
     * Password constraints:
     * 1. It contains at least 8 characters and at most 20 characters.
     * 2. It contains at least one digit.
     * 3. It contains at least one upper case alphabet.
     * 4. It contains at least one lower case alphabet.
     * 5. It contains at least one special character which includes !@#$%&*()-+=^.
     * 6. It doesn’t contain any white space.
     * @param password
     * @return 
     */
    public boolean isPasswordNotValid(String password){

        String regex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&-+=()])(?=\\S+$).{8,20}$";

        boolean result;
        if(password.matches(regex)){
            result = false;
        }
        else{
            result = true;
        }
        return result;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginJLabel = new javax.swing.JLabel();
        backLoginJButton = new javax.swing.JButton();
        homeLoginJButton = new javax.swing.JButton();
        renterEmailidLoginJLabel = new javax.swing.JLabel();
        renterPasswordLoginJLabel = new javax.swing.JLabel();
        emailidLoginJTextField = new javax.swing.JTextField();
        passwordLoginJTextField = new javax.swing.JTextField();
        loginJButton = new javax.swing.JButton();
        validationJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginJLabel.setFont(new java.awt.Font("Garamond", 3, 24)); // NOI18N
        loginJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginJLabel.setText("Login");
        loginJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginJLabel.setName("loginLabel"); // NOI18N

        backLoginJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        backLoginJButton.setText("Back");
        backLoginJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        backLoginJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        backLoginJButton.setName("backLoginJButton"); // NOI18N
        backLoginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLoginJButtonActionPerformed(evt);
            }
        });

        homeLoginJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        homeLoginJButton.setText("Home");
        homeLoginJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        homeLoginJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        homeLoginJButton.setName("homeLoginJButton"); // NOI18N
        homeLoginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeLoginJButtonActionPerformed(evt);
            }
        });

        renterEmailidLoginJLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        renterEmailidLoginJLabel.setText("Email-Id");
        renterEmailidLoginJLabel.setName("renterEmailidLoginJLabel"); // NOI18N

        renterPasswordLoginJLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        renterPasswordLoginJLabel.setText("Password");
        renterPasswordLoginJLabel.setName("renterPasswordLoginJLabel"); // NOI18N

        emailidLoginJTextField.setName("emailidLoginJTextField"); // NOI18N

        passwordLoginJTextField.setName("passwordLoginJTextField"); // NOI18N

        loginJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        loginJButton.setText("Login");
        loginJButton.setName("loginJButton"); // NOI18N
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        validationJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        validationJLabel.setForeground(new java.awt.Color(255, 0, 0));
        validationJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(loginJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backLoginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(94, 94, 94)
                            .addComponent(homeLoginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(renterPasswordLoginJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(loginJButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(passwordLoginJTextField)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(renterEmailidLoginJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(emailidLoginJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(135, 135, 135)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backLoginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeLoginJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(renterEmailidLoginJLabel)
                        .addComponent(emailidLoginJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(renterPasswordLoginJLabel)
                        .addComponent(passwordLoginJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(loginJButton)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backLoginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CreateAccountLoginJFrame_new hjf = new CreateAccountLoginJFrame_new(this.type);
        hjf.setVisible(true);
    }//GEN-LAST:event_backLoginJButtonActionPerformed

    private void homeLoginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeLoginJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeJFrame hjf = new HomeJFrame();
        hjf.setVisible(true);
    }//GEN-LAST:event_homeLoginJButtonActionPerformed

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // TODO add your handling code here:
        
        if(emailidLoginJTextField.getText().isEmpty()){
            validationJLabel.setText("Email Id cannot be Empty!");
        }
        else if(passwordLoginJTextField.getText().isEmpty()){
            validationJLabel.setText("Password cannot be Empty!");
        }
        else if(isEmailNotValid(emailidLoginJTextField.getText())){
            validationJLabel.setText("Email is not Valid!");
        }
        else if(isPasswordNotValid(passwordLoginJTextField.getText())){
            validationJLabel.setText("Password is not Valid!");
        }
        else{
            AbstractCarRentalSystemAPI acra = AbstractCarRentalSystemAPI.getObject();
            AbstractPersonAPI person = null;
            if(type.equalsIgnoreCase("Lessee")) {
                person = acra.getLessee(emailidLoginJTextField.getText(), passwordLoginJTextField.getText());
                if(person != null) {
                    this.dispose();
                    LesseeBookingJFrame lbjf = new LesseeBookingJFrame(person);
                    lbjf.setVisible(true);
                }
            } else if(type.equalsIgnoreCase("Renter")) {
                person = acra.getRenter(emailidLoginJTextField.getText(), passwordLoginJTextField.getText());
                if(person != null) {
                    this.dispose();
                    RenterHomeJFrame rhjf = new RenterHomeJFrame(person);
                    rhjf.setVisible(true);
                }
            } else if(type.equalsIgnoreCase("System")) {
                person = acra.getSystemAdmin(emailidLoginJTextField.getText(), passwordLoginJTextField.getText());
                if(person != null) {
                    this.dispose();
                    SystemHomeJFrame shjf = new SystemHomeJFrame(person);
                    shjf.setVisible(true);
                }
            }

            if(person == null) {
                System.out.println("Wrong credentials");
                JOptionPane.showMessageDialog(null, type + " Wrong credentials!");
                return;
            }
            
            validationJLabel.setForeground(Color.blue);
            validationJLabel.setText("Login Successful!");
        }
        
    }//GEN-LAST:event_loginJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backLoginJButton;
    private javax.swing.JTextField emailidLoginJTextField;
    private javax.swing.JButton homeLoginJButton;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JTextField passwordLoginJTextField;
    private javax.swing.JLabel renterEmailidLoginJLabel;
    private javax.swing.JLabel renterPasswordLoginJLabel;
    private javax.swing.JLabel validationJLabel;
    // End of variables declaration//GEN-END:variables
}
