/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.GUI;

import edu.neu.csye6200.SystemModel.AbstractBookingAPI;
import edu.neu.csye6200.SystemModel.AbstractCarAPI;
import edu.neu.csye6200.SystemModel.AbstractCarRentalSystemAPI;
import edu.neu.csye6200.SystemModel.AbstractPersonAPI;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author manish
 */
public class ManageBookingJFrame extends javax.swing.JFrame {

    AbstractPersonAPI person;
    AbstractBookingAPI booking;
    AbstractCarAPI bookedCar; 
    /**
     * Creates new form ManageBookingJFrame
     */
    public ManageBookingJFrame() {
        initComponents();
    }

    ManageBookingJFrame(AbstractPersonAPI person, AbstractBookingAPI selectedBooking) {
        initComponents();
        this.person = person;
        this.booking = selectedBooking;
        this.bookedCar = AbstractCarRentalSystemAPI.getObject().getCar(booking.getCarId()); 
        this.bookingID.setText(booking.getBookingId().toString());
        this.fee.setText(booking.getFee() + "");
        dateBooking.setText(booking.getDate().format(DateTimeFormatter.ofPattern("MM/dd/yyyy")));//LocalDate.parse(dateBooking.getText()), DateTimeFormatter.ofPattern("MM/dd/yyyy"));
        startTimeBooking.setText(booking.getStartTime().format(DateTimeFormatter.ofPattern("HH:mm:ss")));//.toString());
        endTimeBooking.setText(booking.getEndTime().format(DateTimeFormatter.ofPattern("HH:mm:ss")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bookingID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateBooking = new javax.swing.JTextField();
        startTimeBooking = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        endTimeBooking = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fee = new javax.swing.JLabel();
        updateBooking = new javax.swing.JButton();
        deleteBooking = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Booking ID");

        jLabel2.setText("Date");

        jLabel3.setText("Start Time");

        jLabel4.setText("End Time");

        jLabel5.setText("Fees");

        updateBooking.setText("Update Booking");
        updateBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookingActionPerformed(evt);
            }
        });

        deleteBooking.setText("Delete Booking");
        deleteBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingActionPerformed(evt);
            }
        });

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateBooking)
                        .addGap(27, 27, 27)
                        .addComponent(deleteBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startTimeBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fee, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(endTimeBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(bookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dateBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(startTimeBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(endTimeBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fee, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBooking)
                    .addComponent(deleteBooking))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookingActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this booking?");
        
        if(option == 2 || option == 1)
            return;
        
        StringBuilder sb = new StringBuilder();
        sb.append(booking.getBookingId()).append(",");
        sb.append(person.getPersonId()).append(",");
        sb.append(booking.getCarId()).append(",");
        sb.append(booking.getDate().format(DateTimeFormatter.ofPattern("MM/dd/yyyy"))).append(",");
        sb.append(booking.getStartTime().format(DateTimeFormatter.ofPattern("HH:mm:ss"))).append(",");
        sb.append(booking.getEndTime().format(DateTimeFormatter.ofPattern("HH:mm:ss"))).append(",");
        sb.append(booking.getFee());
        
        System.out.println(sb.toString());
        AbstractCarRentalSystemAPI.getObject().deleteBooking(sb.toString(), booking.getBookingId());
        
        System.out.println("Deleted successfully");
        this.dispose();
        LesseeBookingJFrame lbjf = new LesseeBookingJFrame(person);
        lbjf.setVisible(true);
    }//GEN-LAST:event_deleteBookingActionPerformed

    private void updateBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookingActionPerformed
        // TODO add your handling code here:
        StringBuilder oldBooking = new StringBuilder();
        oldBooking.append(booking.getBookingId()).append(",");
        oldBooking.append(person.getPersonId()).append(",");
        oldBooking.append(booking.getCarId()).append(",");
        oldBooking.append(booking.getDate().format(DateTimeFormatter.ofPattern("MM/dd/yyyy"))).append(",");
        oldBooking.append(booking.getStartTime().format(DateTimeFormatter.ofPattern("HH:mm:ss"))).append(",");
        oldBooking.append(booking.getEndTime().format(DateTimeFormatter.ofPattern("HH:mm:ss"))).append(",");
        oldBooking.append(booking.getFee());
       
        Double newBookingFee = AbstractCarRentalSystemAPI.getObject()
                .getBookingFeeByInstances(LocalTime.parse(startTimeBooking.getText(),
                        DateTimeFormatter.ofPattern("HH:mm:ss")),
                        LocalTime.parse(endTimeBooking.getText(),
                                DateTimeFormatter.ofPattern("HH:mm:ss")),
                    bookedCar);
                
        StringBuilder newBooking = new StringBuilder();
        newBooking.append(booking.getBookingId()).append(",");
        newBooking.append(person.getPersonId()).append(",");
        newBooking.append(booking.getCarId()).append(",");
        newBooking.append(dateBooking.getText()).append(",");
        newBooking.append(startTimeBooking.getText()).append(",");
        newBooking.append(endTimeBooking.getText()).append(",");
        newBooking.append(newBookingFee);

        AbstractCarRentalSystemAPI.getObject().updateBooking(oldBooking.toString(), booking.getBookingId(), newBooking.toString());
        
        System.out.println("Updated successfully");
        
        this.dispose();
        LesseeBookingJFrame lbjf = new LesseeBookingJFrame(person);
        lbjf.setVisible(true);
    }//GEN-LAST:event_updateBookingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LesseeBookingJFrame lbjf = new LesseeBookingJFrame(person);
        lbjf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBookingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookingID;
    private javax.swing.JTextField dateBooking;
    private javax.swing.JButton deleteBooking;
    private javax.swing.JTextField endTimeBooking;
    private javax.swing.JLabel fee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField startTimeBooking;
    private javax.swing.JButton updateBooking;
    // End of variables declaration//GEN-END:variables
}
