/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.GUI;

import edu.neu.csye6200.SystemModel.AbstractCarAPI;
import edu.neu.csye6200.SystemModel.AbstractCarRentalSystemAPI;
import edu.neu.csye6200.SystemModel.AbstractPersonAPI;
import edu.neu.csye6200.SystemModel.Car;
import edu.neu.csye6200.SystemModel.CarFactory;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manish
 */
public class RenterHomeJFrame extends javax.swing.JFrame {

    private AbstractPersonAPI person = null;
    /**
     * Creates new form RenterHomeJFrame
     */
    public RenterHomeJFrame() {
        initComponents();
    }

    public RenterHomeJFrame(AbstractPersonAPI person) {
        this.person = person;
        initComponents();
        helloRenterLabel.setText("Hello " + person.getName());
        DefaultTableModel model = (DefaultTableModel) carList.getModel();
        model.setRowCount(0);
        AbstractCarRentalSystemAPI
                .getObject()
                .getAllCars().stream()
                    .filter(c -> c.getRenterId().equals(this.person.getPersonId()))
                    .forEach(car -> {

                        Object[] row = new Object[3];
                        row[0] = car; // I need car instance later which I'll 
                                      // retrieve from here

                        row[1] = car.getName();
                        row[2] = car.getRentPerHour();
                        model.addRow(row);
                    });
        carList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerCarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        updateCarButton = new javax.swing.JButton();
        deleteCarButton = new javax.swing.JButton();
        helloRenterLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carList = new javax.swing.JTable();
        backSystemLoginJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerCarButton.setText("Register Car");
        registerCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Your Cars");

        updateCarButton.setText("Update Car");
        updateCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCarButtonActionPerformed(evt);
            }
        });

        deleteCarButton.setText("Delete Car");
        deleteCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCarButtonActionPerformed(evt);
            }
        });

        helloRenterLabel.setText("jLabel2");

        carList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Car Company", "Car Name", "Rent Per Hour"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(carList);
        if (carList.getColumnModel().getColumnCount() > 0) {
            carList.getColumnModel().getColumn(0).setResizable(false);
            carList.getColumnModel().getColumn(1).setResizable(false);
            carList.getColumnModel().getColumn(2).setResizable(false);
        }

        backSystemLoginJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        backSystemLoginJButton.setText("Logout");
        backSystemLoginJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        backSystemLoginJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        backSystemLoginJButton.setName("backSystemLoginJButton"); // NOI18N
        backSystemLoginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSystemLoginJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(helloRenterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registerCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(backSystemLoginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(helloRenterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(registerCarButton)
                        .addGap(17, 17, 17)
                        .addComponent(updateCarButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(backSystemLoginJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCarButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        RegisterCarJFrame rcjf = new RegisterCarJFrame(this.person);
        rcjf.setVisible(true);
    }//GEN-LAST:event_registerCarButtonActionPerformed

    private void updateCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCarButtonActionPerformed
        
        if(carList.getModel().getRowCount() == 0 || carList.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a car to update.");
            return;
        }
        
        AbstractCarAPI selectedCar = (AbstractCarAPI) carList.getValueAt(carList.getSelectedRow(), 0);
        
        this.dispose();
        UpdateCarJFrame ucjf = new UpdateCarJFrame(person, selectedCar);
        ucjf.setVisible(true);
    }//GEN-LAST:event_updateCarButtonActionPerformed

    private void deleteCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCarButtonActionPerformed
        if(carList.getModel().getRowCount() == 0 || carList.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a car to delete.");
            return;
        }
        
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this car?");
        
        if(option == 2 || option == 1)
            return;
        
        AbstractCarAPI car = (AbstractCarAPI) carList.getValueAt(carList.getSelectedRow(), 0);
        StringBuilder oldCar = new StringBuilder();
        oldCar.append(car.getCarId()).append(",");
        oldCar.append(person.getPersonId()).append(",");
        oldCar.append(car.getName()).append(",");
        oldCar.append(car.getCompany()).append(",");
        oldCar.append(car.getNumberOfSeats()).append(",");
        oldCar.append(car.getInsuranceCompany()).append(",");
        oldCar.append(car.getInsuranceNumber()).append(",");
        oldCar.append(car.getRentPerHour());

        AbstractCarRentalSystemAPI.getObject().deleteCar(oldCar.toString(), car.getCarId());
        
        this.dispose();
        RenterHomeJFrame rhjf = new RenterHomeJFrame(person);
        rhjf.setVisible(true);
    }//GEN-LAST:event_deleteCarButtonActionPerformed

    private void backSystemLoginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSystemLoginJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeJFrame hjf = new HomeJFrame();
        hjf.setVisible(true);
    }//GEN-LAST:event_backSystemLoginJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RenterHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RenterHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RenterHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RenterHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RenterHomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backSystemLoginJButton;
    private javax.swing.JTable carList;
    private javax.swing.JButton deleteCarButton;
    private javax.swing.JLabel helloRenterLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton registerCarButton;
    private javax.swing.JButton updateCarButton;
    // End of variables declaration//GEN-END:variables
}
