/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.GUI;

import static edu.neu.csye6200.GUI.CreateAccountJFrame.DATE_FORMAT;
import edu.neu.csye6200.SystemModel.AbstractCarRentalSystemAPI;
import edu.neu.csye6200.SystemModel.CarRentalSystemBase;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

/**
 *
 * @author varad
 */
public class SystemCreateAccountJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SystemCreateAccountJFrame
     */
    public SystemCreateAccountJFrame() {
        initComponents();
    }
    
    /**
     * Date format: "MM/dd/yyyy"
     * @param date
     * @return 
     */
    public boolean isDateNotValid(String date) 
    {
            try {
                DateFormat df = new SimpleDateFormat(DATE_FORMAT);
                df.setLenient(false);
                df.parse(date);
                return false;
            } catch (ParseException e) {
                return true;
            }
    }
    
    /**
     * Email format: something@something.com
     * @param email
     * @return 
     */
    public boolean isEmailNotValid(String email){
        String regex = "^(.+)@(.+)$";//"^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        boolean result;
        if(email.matches(regex)){
            result = false;
        }
        else {
            result = true;
        }
        return result;
    }
    
    /**
     * Password constraints:
     * 1. It contains at least 8 characters and at most 20 characters.
     * 2. It contains at least one digit.
     * 3. It contains at least one upper case alphabet.
     * 4. It contains at least one lower case alphabet.
     * 5. It contains at least one special character which includes !@#$%&*()-+=^.
     * 6. It doesn’t contain any white space.
     * @param password
     * @return 
     */
    public boolean isPasswordNotValid(String password){
        String regex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&-+=()])(?=\\S+$).{8,20}$";
        boolean result;
        if(password.matches(regex)){
            result = false;
        }
        else{
            result = true;
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phoneNoDriverJLabel = new javax.swing.JLabel();
        systemPhoneNoJTextField1 = new javax.swing.JTextField();
        homeSystemLoginJButton = new javax.swing.JButton();
        driverCreateAccountJButton = new javax.swing.JButton();
        driverNameJLabel = new javax.swing.JLabel();
        systemNameJTextField = new javax.swing.JTextField();
        systemPasswordLoginJLabel3 = new javax.swing.JLabel();
        systemPasswordJTextField3 = new javax.swing.JTextField();
        systemEmailidLoginJLabel3 = new javax.swing.JLabel();
        systemDOBLoginJTextField1 = new javax.swing.JTextField();
        systemEmailidJTextField3 = new javax.swing.JTextField();
        DateOfBirthDriverJLabel = new javax.swing.JLabel();
        backSystemLoginJButton = new javax.swing.JButton();
        systemCreateAccountJLabel = new javax.swing.JLabel();
        validationJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        phoneNoDriverJLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        phoneNoDriverJLabel.setText("Phone No.");
        phoneNoDriverJLabel.setName("phoneNoDriverJLabel"); // NOI18N

        systemPhoneNoJTextField1.setName("renterPasswordLoginJTextField"); // NOI18N

        homeSystemLoginJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        homeSystemLoginJButton.setText("Home");
        homeSystemLoginJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        homeSystemLoginJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        homeSystemLoginJButton.setName("homeSystemLoginJButton"); // NOI18N
        homeSystemLoginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeSystemLoginJButtonActionPerformed(evt);
            }
        });

        driverCreateAccountJButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        driverCreateAccountJButton.setText("Create Account");
        driverCreateAccountJButton.setName("driverCreateAccountJButton"); // NOI18N
        driverCreateAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverCreateAccountJButtonActionPerformed(evt);
            }
        });

        driverNameJLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        driverNameJLabel.setText("Name");
        driverNameJLabel.setName("driverNameJLabel"); // NOI18N

        systemNameJTextField.setName("systemNameJTextField"); // NOI18N

        systemPasswordLoginJLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        systemPasswordLoginJLabel3.setText("Password");
        systemPasswordLoginJLabel3.setName("systemPasswordLoginJLabel"); // NOI18N

        systemPasswordJTextField3.setName("renterPasswordLoginJTextField"); // NOI18N

        systemEmailidLoginJLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        systemEmailidLoginJLabel3.setText("Email-Id");
        systemEmailidLoginJLabel3.setName("systemEmailidLoginJLabel"); // NOI18N

        systemDOBLoginJTextField1.setName("systemEmailidLoginJTextField"); // NOI18N

        systemEmailidJTextField3.setName("systemEmailidLoginJTextField"); // NOI18N

        DateOfBirthDriverJLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        DateOfBirthDriverJLabel.setText("Date Of Birth");
        DateOfBirthDriverJLabel.setName("DateOfBirthDriverJLabel"); // NOI18N

        backSystemLoginJButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        backSystemLoginJButton.setText("Back");
        backSystemLoginJButton.setMaximumSize(new java.awt.Dimension(150, 50));
        backSystemLoginJButton.setMinimumSize(new java.awt.Dimension(150, 50));
        backSystemLoginJButton.setName("backSystemLoginJButton"); // NOI18N
        backSystemLoginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSystemLoginJButtonActionPerformed(evt);
            }
        });

        systemCreateAccountJLabel.setFont(new java.awt.Font("Garamond", 3, 24)); // NOI18N
        systemCreateAccountJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        systemCreateAccountJLabel.setText("System Create Account");
        systemCreateAccountJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        systemCreateAccountJLabel.setName("systemCreateAccountJLabel"); // NOI18N

        validationJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        validationJLabel.setForeground(new java.awt.Color(255, 0, 0));
        validationJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNoDriverJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(systemEmailidLoginJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(systemPasswordLoginJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateOfBirthDriverJLabel)
                            .addComponent(backSystemLoginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(systemEmailidJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(systemPhoneNoJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(systemDOBLoginJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(systemPasswordJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(homeSystemLoginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(driverCreateAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(systemCreateAccountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(driverNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(systemNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(validationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(systemCreateAccountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driverNameJLabel)
                    .addComponent(systemNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateOfBirthDriverJLabel)
                    .addComponent(systemDOBLoginJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNoDriverJLabel)
                    .addComponent(systemPhoneNoJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(systemEmailidLoginJLabel3)
                    .addComponent(systemEmailidJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(systemPasswordLoginJLabel3)
                    .addComponent(systemPasswordJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(driverCreateAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backSystemLoginJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeSystemLoginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeSystemLoginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeSystemLoginJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeJFrame hjf = new HomeJFrame();
        hjf.setVisible(true);
    }//GEN-LAST:event_homeSystemLoginJButtonActionPerformed

    private void backSystemLoginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSystemLoginJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CreateAccountLoginJFrame_new cajf = new CreateAccountLoginJFrame_new("System");
        cajf.setVisible(true);
    }//GEN-LAST:event_backSystemLoginJButtonActionPerformed

    private void driverCreateAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverCreateAccountJButtonActionPerformed
        // TODO add your handling code here:
        DateFormat dateFormatter = new SimpleDateFormat("MM/dd/yyyy");
        
        if(systemNameJTextField.getText().isEmpty()){
            validationJLabel.setText("Name field cannot be Empty!");
        }
        else if(systemDOBLoginJTextField1.getText().isEmpty()){
            validationJLabel.setText("Date of birth cannot be Empty!");
        }
        else if(systemPhoneNoJTextField1.getText().isEmpty()){
            validationJLabel.setText("Phone number cannot be Empty!");
        }
        else if(systemEmailidJTextField3.getText().isEmpty()){
            validationJLabel.setText("Email Id cannot be Empty!");
        }
        else if(systemPasswordJTextField3.getText().isEmpty()){
            validationJLabel.setText("Password cannot be Empty!");
        }
        else if(isDateNotValid(systemDOBLoginJTextField1.getText())){
            validationJLabel.setText("Date of Birth not Valid!");
        }
        else if(isEmailNotValid(systemEmailidJTextField3.getText())){
            validationJLabel.setText("Email is not Valid!");
        }
        else if(isPasswordNotValid(systemPasswordJTextField3.getText())){
            validationJLabel.setText("Password is not Valid!");
        }
        else{
            StringBuilder sb = new StringBuilder();

            sb.append(systemNameJTextField.getText()).append(",");
            sb.append(systemDOBLoginJTextField1.getText()).append(",");
            sb.append(systemPhoneNoJTextField1.getText()).append(",");
            sb.append(systemEmailidJTextField3.getText()).append(",");
            sb.append(systemPasswordJTextField3.getText());

            String personData = sb.toString();

            AbstractCarRentalSystemAPI acra = AbstractCarRentalSystemAPI.getObject();
            acra.addSystemAdmin(personData);
            this.dispose();
            CreateAccountLoginJFrame_new cajf = new CreateAccountLoginJFrame_new("System");
            cajf.setVisible(true);
        }
    }//GEN-LAST:event_driverCreateAccountJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemCreateAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemCreateAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemCreateAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemCreateAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemCreateAccountJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateOfBirthDriverJLabel;
    private javax.swing.JButton backSystemLoginJButton;
    private javax.swing.JButton driverCreateAccountJButton;
    private javax.swing.JLabel driverNameJLabel;
    private javax.swing.JButton homeSystemLoginJButton;
    private javax.swing.JLabel phoneNoDriverJLabel;
    private javax.swing.JLabel systemCreateAccountJLabel;
    private javax.swing.JTextField systemDOBLoginJTextField1;
    private javax.swing.JTextField systemEmailidJTextField3;
    private javax.swing.JLabel systemEmailidLoginJLabel3;
    private javax.swing.JTextField systemNameJTextField;
    private javax.swing.JTextField systemPasswordJTextField3;
    private javax.swing.JLabel systemPasswordLoginJLabel3;
    private javax.swing.JTextField systemPhoneNoJTextField1;
    private javax.swing.JLabel validationJLabel;
    // End of variables declaration//GEN-END:variables
}
